// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wapbeuabngeeevjabadu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcGJldWFibmdlZWV2amFiYWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDU4NjAsImV4cCI6MjA3MTY4MTg2MH0.Y7buQ7pZ5FKz_PRxNPBHffit-avPbCc8fZm78uSfIlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});